[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1ZVEfzCM1wiGpyxS80fQMHR5kM1KcMOgc7UqQtHTun8E/edit?gid=0#gid=0"

type = "service_account"
project_id = "manis-learning"
private_key_id = "cb914a661a3177d2f7b0ccaa65e5398dd04d6e30"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDqsnOBTsYsqb3N
boLhLxxBD8TY6+U+rhneKVSdaYr8mAIFYkBUA3zOa4WYQVPYQEQrJ5a8yTMPtJ/Q
jXslH07WSWxtOTtaif0cv4p3SO/2v2xhCfELGEENwpXDRW3nnbBEhPoZOhw4MLMA
OwUsIzftv+80aFZtC7xtII3W347Q/atdZjZjzKkBN4fcUqgiqAC3aJyaacPzy4g8
R0e6VULAVQ20XFmZHZ0wU9Pbu5TluPNJQxNWwlE+IWlkclxVCA1SC/RdSXqxjfbg
/nzC7JfFki6LMFSArfz6W6LvhtVw7++stHPGbRavlfa789zlhMRs/rm0eK2OV1XR
X7OLXh05AgMBAAECggEAaZo3F8FKsVEFGrj1gf5RH8NJJvPpuCzdbdW6AYQ6ahK5
ohOF72eMUlMWDx6h6+Vq5uIO1M5RP+ldmZj3hooSTqBF/dVpLAF31uYmlyrF8ohK
a1VuVLgqmVbrTSxh2fxdkk8lO5Gmne/nsxxbZPNJ2JvqtXGXJcTImW+y8rKvz7/f
tDAgeR7R3fE362MH37ktIq795DbxV4bascvQGL7vdgk4xwTOozVPJHCYybQIY1nv
wr/cvCY5AzK1xvEaOFT0wdbxDdQm93ifx+YLIyIpntZgN73s19xW4SF5jHSiM4hb
SrnLTgSvAYhEFAt+3yoFpAAWXcAgxfu+bfQYseG7ewKBgQD1V2KpFo8nf19oo2jD
jVxnClpqJeU2JlAu22OKzOkSW0EJSLpaEqMcGNv5EqH1k5fwGm0gWqnseGd/x/Of
xFghM7Lw/M13ik1qZeVFpkMsr1drxkIR4jRSnobc2r8/8lVakpcX1lpstQcOZAZx
xYw9fvgEuYiv8Jfcr5eUlZoYXwKBgQD05K7svO14/ixm1pSWcuY88obgOlqrlZS2
0IXkvnKSh3EVPQxGHPzRJQNrGyYqhd8PKnshHO2zomrQCOQ2I67BAR/i8Oa3cTQU
hHVhaiYfqugICoPLtmLuZ0UkwrV6Ru4Jq413KgRFJJqfQtttVTkfUm/jE0RZ/BwX
RikjWUARZwKBgBOIq6BO3YMFjzEjoZnATZUeq+g7sC5JiqTQbvKEMiJ2BY2Zrsyx
Iy9/gzQnmaGV6MkDMaEb1t+vDn6MCwezeFjcZujtF+bmqhdImaKcBEkwhMNd+7C0
0/moCZDYEdYjk0ws077gID77gt5QdHrmga37x/+ITivD+jNl/6mi56v9AoGAakHf
dHD1SQ5gDa8FgdIQ/FjvFNO9C743bKtFrV7FL7b85g47CSECwWyh8xMwmDrF8jqo
elGnAc5zMhjpjGQnKy9lun50XRwNUOm4VLBOImdxjiuhy/4zJuZAJhclzwx/tEpv
c0kT2TxsqrXDp8jWpDSMv6ZYfgLZ3W9f4iqTlfkCgYAaBrEDY7rC2BEJudgEtyOt
nYGN8sL+dyOtQqvXfBjKUNiZUO+z012g44/89CvWdryqA07yhz4r+f6Px3vur9eLv
Bb2D7YsN4nM1FCAy1m+w2FuNxKYtDS2pD4AaQ4EAVvsuu+tfOOUEOElN8vGeO5fc
upOdK6s7aRwsa2t4Q7bAoA==
-----END PRIVATE KEY-----
"""
client_email = "titech-ayesha@manis-learning.iam.gserviceaccount.com"
client_id = "107682103643336875188"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/titech-ayesha%40manis-learning.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
